services:
  redis:
    image: redis:7.0.4
    ports:
      - 6379:6379
  postgres:
    image: postgres:14.5
    env_file:
      - .env
    ports:
      - 5432:5432
  backend:
    image: node:16.17.0
    ports:
      - 4000:4000
    command: yarn dev
    volumes:
      - marketplace-backend-nodemodules:/usr/src/service/backend/node_modules
      - ./backend:/usr/src/service/backend
    working_dir: /usr/src/service/backend
    depends_on:
      - redis
      - postgres
  frontend:
    image: node:16.17.0
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - marketplace-frontend-nodemodules:/usr/src/service/frontend/node_modules
      - ./frontend:/usr/src/service/frontend
    working_dir: /usr/src/service/frontend
    depends_on:
      - backend
volumes:
  marketplace-backend-nodemodules:
    external: true
  marketplace-frontend-nodemodules:
    external: true
