version: '2'
services:
  backend-base:
    image: node:16.17.0
    volumes:
      - marketplace-backend-nodemodules:/usr/src/service/backend/node_modules
      - ./backend:/usr/src/service/backend
    working_dir: /usr/src/service/backend
  backend-install:
    extends:
      service: backend-base
    command: npm i

  frontend-base:
    image: node:16.17.0
    volumes:
      - marketplace-frontend-nodemodules:/usr/src/service/frontend/node_modules
      - ./frontend:/usr/src/service/frontend
    working_dir: /usr/src/service/frontend
  frontend-install:
    extends:
      service: frontend-base
    command: npm i
  frontend-gen:
    extends:
      service: frontend-base
    command: npm run gen
volumes:
  marketplace-backend-nodemodules:
    external: true
  marketplace-frontend-nodemodules:
    external: true
